sudo: required
language: generic

services:
  - docker

before_install:
 - docker build -t shaheer37/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shaheer37/docker-react npm run test
